#!/usr/bin/env python3
"""
Migration 009: Backfill embeddings untuk 3 topic + 5 opinion existing.

Hardcoded data (dari observasi Supabase MCP):
  - 3 topics di discussion_rooms: ...010, ...011, ...012
  - 5 opinions: ...020, ...021, ...022, ...023, ...024

Tidak butuh psycopg2 — data hardcoded. Hanya butuh:
  - Python3 stdlib (urllib, json)
  - OPENROUTER_API_KEY env var

Usage:
  export OPENROUTER_API_KEY=sk-or-v1-...
  python3 009_backfill_embeddings.py > 009_backfill_embeddings.sql

Apply:
  psql -U postgres -d konect -f 009_backfill_embeddings.sql
"""
import os
import sys
import json
import urllib.request

OPENROUTER_URL = "https://openrouter.ai/api/v1/embeddings"
MODEL = "openai/text-embedding-3-small"
DIM = 1536

# Data dari observasi Supabase MCP
TOPICS = [
    ("00000000-0000-0000-0000-000000000010",
     "Musyawarah Anggaran Tahunan 2026",
     "Bagaimana alokasi SHU tahun ini? Mohon pendapat anggota terkait prioritas program."),
    ("00000000-0000-0000-0000-000000000011",
     "Usul penambahan unit usaha simpan pinjam",
     "Banyak anggota yang membutuhkan akses pinjaman cepat dengan bunga ringan."),
    ("00000000-0000-0000-0000-000000000012",
     "Transparansi laporan keuangan Q1",
     "Berikut ringkasan keuangan triwulan I. Mohon review dan masukan dari anggota."),
]

OPINIONS = [
    ("00000000-0000-0000-0000-000000000020",
     "SHU tahun ini sebaiknya dialokasikan 60% untuk cadangan dan 40% untuk jasa modal anggota."),
    ("00000000-0000-0000-0000-000000000021",
     "Koperasi perlu membuka unit usaha baru: toko sarana produksi pertanian."),
    ("00000000-0000-0000-0000-000000000022",
     "Jasa pinjaman sebaiknya diturunkan dari 1.5% ke 1.2% per bulan untuk anggota."),
    ("00000000-0000-0000-0000-000000000023",
     "Setuju, akses pinjaman cepat sangat dibutuhkan terutama untuk modal usaha tani."),
    ("00000000-0000-0000-0000-000000000024",
     "Laporan keuangan Q1 sudah cukup transparan, perlu ditambah grafik perbandingan tahun lalu."),
]


def get_embedding(text: str, api_key: str) -> list[float]:
    """Call OpenRouter embeddings API, return 1536-dim vector."""
    req = urllib.request.Request(
        OPENROUTER_URL,
        data=json.dumps({"model": MODEL, "input": text}).encode(),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read())
    vec = data["data"][0]["embedding"]
    if len(vec) != DIM:
        raise ValueError(f"dim mismatch: got {len(vec)}, expected {DIM}")
    return vec


def vec_to_sql(vec: list[float]) -> str:
    """Format vector as Postgres vector literal."""
    return "[" + ",".join(f"{x:.7f}" for x in vec) + "]"


def main():
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        print("ERROR: set OPENROUTER_API_KEY env var", file=sys.stderr)
        sys.exit(1)

    print("-- Auto-generated by 009_backfill_embeddings.py")
    print(f"-- Model: {MODEL}, Dim: {DIM}")
    print(f"-- Generated: {os.popen('date').read().strip()}")
    print("-- DO NOT EDIT, re-run script to regenerate\n")
    print("begin;")
    print()

    print(f"-- Topics ({len(TOPICS)}):")
    for tid, title, desc in TOPICS:
        text = f"{title}. {desc}".strip()
        sys.stderr.write(f"  computing topic: {title[:50]}...\n")
        sys.stderr.flush()
        vec = get_embedding(text, api_key)
        print(
            f"UPDATE public.discussion_rooms SET embedding = '{vec_to_sql(vec)}'::vector "
            f"WHERE id = '{tid}';"
        )
    print()

    print(f"-- Opinions ({len(OPINIONS)}):")
    for oid, content in OPINIONS:
        sys.stderr.write(f"  computing opinion: {content[:50]}...\n")
        sys.stderr.flush()
        vec = get_embedding(content, api_key)
        print(
            f"UPDATE public.opinions SET embedding = '{vec_to_sql(vec)}'::vector "
            f"WHERE id = '{oid}';"
        )
    print()

    print("commit;")
    print()
    print("-- Verify")
    print("SELECT count(*) AS topics_with_emb FROM discussion_rooms WHERE embedding IS NOT NULL;")
    print("SELECT count(*) AS opinions_with_emb FROM opinions WHERE embedding IS NOT NULL;")


if __name__ == "__main__":
    main()
