/// Data model untuk tabel `discussion_rooms`.
///
/// Field mapping ke schema PostgreSQL:
///   id              → id (UUID, auto-generated by DB)
///   cooperativeId   → cooperative_id (FK → cooperatives.id)
///   createdBy       → created_by (FK → users.id)
///   title           → title
///   description     → description
///   isActive        → is_active
///   isAnonymous     → is_anonymous
///   createdAt       → created_at
///   updatedAt       → updated_at
class DiscussionRoom {
  final String id;
  final String cooperativeId;
  final String createdBy;
  final String title;
  final String? description;
  final bool isActive;
  final bool isAnonymous;
  final DateTime createdAt;
  final DateTime updatedAt;

  const DiscussionRoom({
    required this.id,
    required this.cooperativeId,
    required this.createdBy,
    required this.title,
    this.description,
    this.isActive = true,
    this.isAnonymous = false,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DiscussionRoom.fromJson(Map<String, dynamic> json) {
    return DiscussionRoom(
      id: json['id'] ?? '',
      cooperativeId: json['cooperative_id'] ?? '',
      createdBy: json['created_by'] ?? '',
      title: json['title'] ?? '',
      description: json['description'],
      isActive: json['is_active'] ?? true,
      isAnonymous: json['is_anonymous'] ?? false,
      createdAt: DateTime.tryParse(json['created_at'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updated_at'] ?? '') ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'cooperative_id': cooperativeId,
      'created_by': createdBy,
      'title': title,
      'description': description,
      'is_active': isActive,
      'is_anonymous': isAnonymous,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// JSON payload untuk INSERT ke `discussion_rooms`.
  /// Exclude `id`, `created_at`, `updated_at` (auto-generated by DB).
  /// `is_active` juga default true di DB, tapi dikirim eksplisit untuk kejelasan.
  Map<String, dynamic> toCreateJson() {
    return {
      'cooperative_id': cooperativeId,
      'created_by': createdBy,
      'title': title,
      'description': description,
      'is_active': isActive,
      'is_anonymous': isAnonymous,
    };
  }

  /// JSON untuk penyimpanan di local storage (SharedPreferences).
  /// Menyimpan semua field termasuk id, created_at, updated_at
  /// agar data tetap utuh saat di-reload dari disk.
  Map<String, dynamic> toLocalJson() {
    return {
      'id': id,
      'cooperative_id': cooperativeId,
      'created_by': createdBy,
      'title': title,
      'description': description,
      'is_active': isActive,
      'is_anonymous': isAnonymous,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Factory dari JSON local storage.
  /// Sama dengan fromJson, tapi diekspos eksplisit untuk konsistensi.
  factory DiscussionRoom.fromLocalJson(Map<String, dynamic> json) {
    return DiscussionRoom.fromJson(json);
  }

  DiscussionRoom copyWith({
    String? id,
    String? cooperativeId,
    String? createdBy,
    String? title,
    String? description,
    bool? isActive,
    bool? isAnonymous,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return DiscussionRoom(
      id: id ?? this.id,
      cooperativeId: cooperativeId ?? this.cooperativeId,
      createdBy: createdBy ?? this.createdBy,
      title: title ?? this.title,
      description: description ?? this.description,
      isActive: isActive ?? this.isActive,
      isAnonymous: isAnonymous ?? this.isAnonymous,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
